spring:
    datasource:
        url: jdbc:mysql://localhost:3306/autenticador?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password:

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 314334265010-bp2bml0fua1jfqoq372thfgbikft57kr.apps.googleusercontent.com
                        clientSecret: vTIfZlgIjCr-8TIixvt29RUC
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - email
                            - profile

app:
    auth:
        tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
        tokenExpirationMsec: 864000000
    oauth2:
        authorizedRedirectUris:
            - http://localhost:3000/aouth2/redirect
            - myandroidapp://oauth2/redirec
            - mysiosapp://oauth2/redirect

